name: games_services_platform_interface
description: A common platform interface for the games_services plugin.
homepage: https://github.com/Abedalkareem/games_services
version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter