name: games_services_platform_interface
description: A common platform interface for the games_services plugin.
homepage: https://github.com/Abedalkareem/games_services
version: 2.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0