-keep class com.abedalkareem.games_services.models.AchievementItemData { <fields>; }
-keep class com.abedalkareem.games_services.models.LeaderboardScoreData { <fields>; }
-keep class com.abedalkareem.games_services.models.SavedGame { <fields>; }
