name: games_services_example
description: Demonstrates how to use the games_services plugin.
publish_to: 'none'
version: 2.0.0


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  games_services:
    path: ../

flutter:

  uses-material-design: true