name: Github Actions
on:
    pull_request:
      branches:
        - develop
        - master
    push:
      branches:
        - develop
        - master

defaults:
  run:
    working-directory: games_services/example

jobs:
  build_android:
    name: Build Android
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - run: flutter pub get
      - run: flutter build appbundle

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - run: flutter pub get
      - run: flutter build ios --no-codesign

  build_macos:
    name: Build macOS
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - run: flutter pub get
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
