name: Github Actions
on:
    pull_request:
      branches:
        - develop
        - master
    push:
      branches:
        - develop
        - master

defaults:
  run:
    working-directory: games_services/example

jobs:
  build_android:
    name: Build Android
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter pub get
      - run: flutter build appbundle

  # Works on emulator and real device.
  #No idea why not here.
  # build_ios:
  #   name: Build iOS
  #   runs-on: macos-latest
  #   timeout-minutes: 30
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "dev"
  #     - run: flutter pub get
  #     - run: flutter build ios --no-codesign
